"""
Generate every .ghuser source bundle from the scripts and the port spec.

Six bundles are produced: three components, each in a Rhino 7 IronPython
flavour and a Rhino 8 Python 3 flavour.

    src/ghuser/rhino7/<Component>/{code.py,metadata.json,icon.png}
    src/ghuser/rhino8/<Component>/{code.py,metadata.json,icon.png}

Sources of truth stay where they were:

    src/rhino7/*.py, src/rhino8/*.py    the algorithms
    tools/ghuser_spec.py                the ports
    tools/icons/*.png                   the icons

Nothing in src/ghuser is written by hand. The generated files are committed so
a bundle can be built without running this first, and --check proves they have
not drifted from their sources.

The two flavours need different code shapes:

  rhino7  GhPython advanced mode wants a class deriving from
          ghpythonlib.componentbase.executingcomponent, so the script's
          module-level entry point is replaced by that wrapper.

  rhino8  The Python 3 script component already recognises the
          Script_Instance(GH_ScriptInstance) class the SDK scripts define, so
          the code is copied verbatim apart from a generated-file marker.

Usage
-----
    python3 tools/build_ghuser_bundles.py            # regenerate
    python3 tools/build_ghuser_bundles.py --check    # verify only
"""

from __future__ import print_function

import argparse
import io
import json
import os
import shutil
import sys

# The repository can live on a filesystem whose timestamp resolution is coarse
# enough that a freshly edited ghuser_spec.py keeps the same mtime second as
# its cached bytecode. Python would then import the stale spec and happily
# report the bundles as in sync while generating them from the old ports.
sys.dont_write_bytecode = True

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ghuser_spec import COMPONENTS, FLAVOURS  # noqa: E402


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICON_DIR = os.path.join(REPO_ROOT, "tools", "icons")

ENTRY_MARKER = (
    "# ============================================================"
    "=================\n# GHPYTHON ENTRY POINT"
)

IPY_HEADER = '''"""
GENERATED FILE - DO NOT EDIT.

Generated by tools/build_ghuser_bundles.py from:
    {source}

Edit the script above and regenerate. Editing this file directly makes the
User Object disagree with the script the project verifies.

Run `python3 tools/build_ghuser_bundles.py --check` to confirm they are in
sync.
"""

'''

CPY_MARKER = """# GENERATED FILE - DO NOT EDIT.
# Generated by tools/build_ghuser_bundles.py from:
#     {source}
# Run `python3 tools/build_ghuser_bundles.py --check` to verify.
"""

IPY_WRAPPER = '''
# =============================================================================
# GHPYTHON USER OBJECT ENTRY POINT
# =============================================================================
#
# GhPython advanced mode. The component ports are declared in metadata.json and
# are baked into the .ghuser, so unlike the plain script version there is
# nothing to create by hand on the canvas.

from ghpythonlib.componentbase import executingcomponent as component


class {class_name}(component):
    """{docline}"""

    def RunScript(self, {params}):
        try:
            return execute(
{args}
            )

        except Exception as exception:
{fallback}
'''


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def build_fallback(outputs, tree_outputs):
    """Build the runtime-error branch, matching the script's own fallback."""
    lines = []

    for output in outputs:
        name = output["name"]

        if name == "Report":
            continue

        if name in tree_outputs:
            lines.append("            {0} = DataTree[object]()".format(name))
        else:
            lines.append("            {0} = []".format(name))

    lines.append("")
    lines.append("            Report = [")
    lines.append('                "Status: Runtime Error",')
    lines.append('                "Error Type: {0}".format(')
    lines.append("                    type(exception).__name__")
    lines.append("                ),")
    lines.append('                "Error Message: {0}".format(')
    lines.append("                    str(exception)")
    lines.append("                ),")
    lines.append(
        '                "Check the component inputs and Rhino geometry '
        'validity."'
    )
    lines.append("            ]")
    lines.append("")
    lines.append("            return (")

    for index, output in enumerate(outputs):
        comma = "," if index < len(outputs) - 1 else ""
        lines.append("                {0}{1}".format(output["name"], comma))

    lines.append("            )")

    return "\n".join(lines)


def render_ironpython_code(component, source_relative):
    script = read(os.path.join(REPO_ROOT, source_relative))
    index = script.find(ENTRY_MARKER)

    if index == -1:
        raise SystemExit(
            "Entry-point marker not found in {0}. The script layout changed; "
            "update ENTRY_MARKER.".format(source_relative)
        )

    body = script[:index].rstrip("\n")

    # The generated file gets its own header, and the port tables the original
    # docstring documents now live in metadata.json.
    if body.startswith('"""'):
        closing = body.find('"""', 3)
        if closing != -1:
            body = body[closing + 3:].lstrip("\n")

    names = [parameter["name"] for parameter in component["inputs"]]
    args = "\n".join(
        "                {0}{1}".format(
            name, "," if i < len(names) - 1 else ""
        )
        for i, name in enumerate(names)
    )

    wrapper = IPY_WRAPPER.format(
        class_name=component["name"],
        docline=component["docline"],
        params=", ".join(names),
        args=args,
        fallback=build_fallback(
            component["outputs"], component["tree_outputs"]
        ),
    )

    return IPY_HEADER.format(source=source_relative) + body + "\n" + wrapper


def render_cpython_code(component, source_relative):
    script = read(os.path.join(REPO_ROOT, source_relative))
    lines = script.split("\n")

    # `#! python 3` must stay on the first line: it is how the Rhino 8 script
    # component picks its language.
    if lines and lines[0].startswith("#!"):
        marker = CPY_MARKER.format(source=source_relative)
        return lines[0] + "\n" + marker + "\n".join(lines[1:])

    raise SystemExit(
        "{0} does not start with a '#!' language line; the Rhino 8 bundle "
        "needs one.".format(source_relative)
    )


def render_metadata(component, flavour_key):
    flavour = FLAVOURS[flavour_key]

    ghpython = {
        "hideOutput": True,
        "hideInput": True,
        "iconDisplay": 0,
        "inputParameters": component["inputs"],
        "outputParameters": component["outputs"],
    }

    if flavour["interpreter"] == "ironpython":
        # Only the IronPython componentizer reads this, and it must be true
        # because the generated code defines a RunScript class.
        ghpython["isAdvancedMode"] = True

    data = {
        "name": component["name"],
        "nickname": component["nickname"],
        "category": flavour["category"],
        "subcategory": flavour["subcategory"],
        "description": component["description"],
        "exposure": 2,
        "instanceGuid": component["instance_guids"][flavour_key],
        "ghpython": ghpython,
    }

    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def bundle_directory(component, flavour_key):
    return os.path.join(
        REPO_ROOT,
        "src",
        "ghuser",
        FLAVOURS[flavour_key]["directory"],
        component["name"],
    )


def targets(component, flavour_key):
    """Return [(path, expected_bytes_or_text, is_binary), ...]."""
    directory = bundle_directory(component, flavour_key)
    source = component["sources"][flavour_key]

    if FLAVOURS[flavour_key]["interpreter"] == "ironpython":
        code = render_ironpython_code(component, source)
    else:
        code = render_cpython_code(component, source)

    icon_path = os.path.join(ICON_DIR, component["icon"] + ".png")

    if not os.path.exists(icon_path):
        raise SystemExit(
            "Missing {0}. Run `python3 tools/make_icons.py`.".format(icon_path)
        )

    with open(icon_path, "rb") as handle:
        icon = handle.read()

    return [
        (os.path.join(directory, "code.py"), code, False),
        (
            os.path.join(directory, "metadata.json"),
            render_metadata(component, flavour_key),
            False,
        ),
        (os.path.join(directory, "icon.png"), icon, True),
    ]


def main():
    parser = argparse.ArgumentParser(description="Generate .ghuser bundles.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed bundles without writing",
    )
    arguments = parser.parse_args()

    failures = 0
    written = 0

    for flavour_key in sorted(FLAVOURS):
        for component in COMPONENTS:
            for path, expected, is_binary in targets(component, flavour_key):
                relative = os.path.relpath(path, REPO_ROOT)

                if arguments.check:
                    if not os.path.exists(path):
                        print("MISSING  {0}".format(relative))
                        failures += 1
                        continue

                    if is_binary:
                        with open(path, "rb") as handle:
                            actual = handle.read()
                    else:
                        actual = read(path)

                    if actual != expected:
                        print("STALE    {0}".format(relative))
                        failures += 1

                    continue

                directory = os.path.dirname(path)

                if not os.path.isdir(directory):
                    os.makedirs(directory)

                if is_binary:
                    shutil.copyfile(
                        os.path.join(
                            ICON_DIR, component["icon"] + ".png"
                        ),
                        path,
                    )
                else:
                    with io.open(path, "w", encoding="utf-8") as handle:
                        handle.write(expected)

                written += 1

    if arguments.check:
        if failures:
            print(
                "\n{0} file(s) out of sync. Run "
                "`python3 tools/build_ghuser_bundles.py` and commit the "
                "result.".format(failures)
            )
            return 1

        print("All bundles are in sync with their sources.")
        return 0

    print("Wrote {0} file(s) across {1} bundles.".format(
        written, len(COMPONENTS) * len(FLAVOURS)
    ))
    return 0


if __name__ == "__main__":
    sys.exit(main())
