"""
Derive GhPython User Object code.py files from the Rhino 7 scripts.

The scripts in src/rhino7 stay the single source of truth. A .ghuser bundle
needs the same algorithm wrapped in a GhPython advanced-mode class instead of
the module-level entry point, so this tool swaps the entry point and writes
src/ghuser/components/<Name>/code.py.

The generated code.py is committed so that a bundle can be built without
running this tool first. Use --check in review or CI to prove the committed
file still matches its source.

Usage
-----
    python3 tools/build_ghuser_code.py            # regenerate every code.py
    python3 tools/build_ghuser_code.py --check    # verify, do not write

Run this from the repository root. It is plain Python 3 and does not need
Rhino, IronPython or GH_IO.dll; those are only needed by the componentizer
step that turns a bundle into a .ghuser.
"""

from __future__ import print_function

import argparse
import io
import os
import sys


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ENTRY_MARKER = (
    "# ============================================================"
    "=================\n# GHPYTHON ENTRY POINT"
)

HEADER_TEMPLATE = '''"""
GENERATED FILE - DO NOT EDIT.

Generated by tools/build_ghuser_code.py from:
    {source}

Edit the Rhino 7 script above and regenerate. Editing this file directly
makes the User Object disagree with the script the project verifies.

Run `python3 tools/build_ghuser_code.py --check` to confirm the two are in
sync.
"""

'''

WRAPPER_TEMPLATE = '''
# =============================================================================
# GHPYTHON USER OBJECT ENTRY POINT
# =============================================================================
#
# GhPython advanced mode. The component ports are declared in metadata.json
# and are baked into the .ghuser, so unlike the plain script version there is
# nothing to create by hand on the canvas.

from ghpythonlib.componentbase import executingcomponent as component


class {class_name}(component):
    """{docline}"""

    def RunScript(self, {params}):
        try:
            return execute(
{args}
            )

        except Exception as exception:
{fallback}
'''


COMPONENTS = [
    {
        "name": "SolarDesignVoxelizer",
        "class_name": "SolarDesignVoxelizer",
        "source": "src/rhino7/SolarDesignVoxelizer_Rhino7_GhPython.py",
        "docline": "Split a DesignVolume into numbered, traceable column voxels.",
        "inputs": ["DesignVolume", "VoxelSizeXY", "VoxelSizeZ", "Run"],
        "outputs": [
            "Voxels",
            "VoxelIDs",
            "ColumnIDs",
            "LayerIDs",
            "VoxelCenters",
            "VoxelVolumes",
            "VoxelTree",
            "Report",
        ],
        "tree_outputs": ["VoxelTree"],
    },
]


def build_fallback(outputs, tree_outputs):
    """Build the runtime-error branch, matching the script's own fallback."""
    lines = []

    for name in outputs:
        if name == "Report":
            continue
        if name in tree_outputs:
            lines.append("            {0} = DataTree[object]()".format(name))
        else:
            lines.append("            {0} = []".format(name))

    lines.append("")
    lines.append("            Report = [")
    lines.append('                "Status: Runtime Error",')
    lines.append('                "Error Type: {0}".format(')
    lines.append("                    type(exception).__name__")
    lines.append("                ),")
    lines.append('                "Error Message: {0}".format(')
    lines.append("                    str(exception)")
    lines.append("                ),")
    lines.append(
        '                "Check the component inputs and Rhino geometry '
        'validity."'
    )
    lines.append("            ]")
    lines.append("")
    lines.append("            return (")

    for index, name in enumerate(outputs):
        comma = "," if index < len(outputs) - 1 else ""
        lines.append("                {0}{1}".format(name, comma))

    lines.append("            )")

    return "\n".join(lines)


def render(component):
    """Return the full generated code.py text for one component."""
    source_path = os.path.join(REPO_ROOT, component["source"])

    with io.open(source_path, encoding="utf-8") as handle:
        script = handle.read()

    index = script.find(ENTRY_MARKER)

    if index == -1:
        raise SystemExit(
            "Entry-point marker not found in {0}. The script layout changed; "
            "update ENTRY_MARKER.".format(component["source"])
        )

    body = script[:index].rstrip("\n")

    # Drop the original module docstring: the generated file gets its own
    # header, and the port tables it documents are now in metadata.json.
    if body.startswith('"""'):
        closing = body.find('"""', 3)
        if closing != -1:
            body = body[closing + 3:].lstrip("\n")

    params = ", ".join(component["inputs"])
    args = "\n".join(
        "                {0}{1}".format(
            name, "," if i < len(component["inputs"]) - 1 else ""
        )
        for i, name in enumerate(component["inputs"])
    )

    wrapper = WRAPPER_TEMPLATE.format(
        class_name=component["class_name"],
        docline=component["docline"],
        params=params,
        args=args,
        fallback=build_fallback(
            component["outputs"], component["tree_outputs"]
        ),
    )

    header = HEADER_TEMPLATE.format(source=component["source"])

    return header + body + "\n" + wrapper


def target_path(component):
    return os.path.join(
        REPO_ROOT,
        "src",
        "ghuser",
        "components",
        component["name"],
        "code.py",
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed code.py files without writing",
    )
    arguments = parser.parse_args()

    failures = 0

    for component in COMPONENTS:
        expected = render(component)
        path = target_path(component)
        relative = os.path.relpath(path, REPO_ROOT)

        if arguments.check:
            if not os.path.exists(path):
                print("MISSING  {0}".format(relative))
                failures += 1
                continue

            with io.open(path, encoding="utf-8") as handle:
                actual = handle.read()

            if actual != expected:
                print("STALE    {0}".format(relative))
                failures += 1
            else:
                print("OK       {0}".format(relative))
            continue

        directory = os.path.dirname(path)

        if not os.path.isdir(directory):
            os.makedirs(directory)

        with io.open(path, "w", encoding="utf-8") as handle:
            handle.write(expected)

        print("WROTE    {0}".format(relative))

    if failures:
        print(
            "\n{0} generated file(s) out of sync. Run "
            "`python3 tools/build_ghuser_code.py` and commit the "
            "result.".format(failures)
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
